import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron'

import type {
  AgentMailConfigInput,
  AgentActionRequest,
  AgentConfirmationInput,
  AgentEntityReference,
  AgentProgressEvent,
  AgentMessageInput,
  AgentUserDataSearchInput,
  AuthLoginInput,
  AuthRegisterInput,
    BackendConfig,
    BackendSessionState,
    CreateAgentMailMessageInput,
    CreateAppTokenInput,
    CreateMemoryInput,
    EcosystemUserDataActionRequest,
  CreateNoteInput,
  CreateReminderInput,
  CreateTaskInput,
    FridayApi,
    ListAgentMailContactsInput,
    ListAgentMailMessagesInput,
    LocalSessionInput,
    PersistedAppState,
    ScheduleTextInput,
    SendTextInput,
    TelegramRemoteConfig,
    UpsertAgentMailContactInput,
    UpsertAgentMailAccountInput,
  UpdateNoteInput,
  UpdateMemoryInput,
  UpdateReminderInput,
  UpdateSettingsInput,
  UpdateTaskInput,
  VpnConfig,
  VoiceCancelSessionInput,
  VoiceFinishSessionInput,
  VoicePushAudioInput,
  VoiceRuntimeConfig,
  VoiceRuntimeEvent,
  VoiceSpeakInput,
} from '../src/shared/contracts'

const api: FridayApi = {
  app: {
    getDiagnostics: () => ipcRenderer.invoke('app:get-diagnostics'),
    getSystemSnapshot: () => ipcRenderer.invoke('app:get-system-snapshot'),
    getState: () => ipcRenderer.invoke('app:get-state'),
    saveState: (state: PersistedAppState) => ipcRenderer.invoke('app:save-state', state),
    getAiRuntimeConfig: () => ipcRenderer.invoke('app:get-ai-runtime-config'),
    restartAsAdmin: () => ipcRenderer.invoke('app:restart-as-admin'),
  },
  agentmail: {
    getConfig: () => ipcRenderer.invoke('agentmail:get-config'),
    saveConfig: (config: AgentMailConfigInput) => ipcRenderer.invoke('agentmail:save-config', config),
    installSkill: () => ipcRenderer.invoke('agentmail:install-skill'),
  },
  telegram: {
    getConfig: () => ipcRenderer.invoke('telegram:get-config'),
    saveConfig: (config: TelegramRemoteConfig) => ipcRenderer.invoke('telegram:save-config', config),
    getState: () => ipcRenderer.invoke('telegram:get-state'),
    start: () => ipcRenderer.invoke('telegram:start'),
    stop: () => ipcRenderer.invoke('telegram:stop'),
    createPairCode: () => ipcRenderer.invoke('telegram:create-pair-code'),
    removeUser: (id: number) => ipcRenderer.invoke('telegram:remove-user', id),
  },
  gateway: {
    ensureRunning: () => ipcRenderer.invoke('gateway:ensure-running'),
  },
  scheduler: {
    scheduleText: (input: ScheduleTextInput) => ipcRenderer.invoke('scheduler:schedule-text', input),
  },
  chat: {
    newSession: () => ipcRenderer.invoke('chat:new-session'),
    sendText: (input: SendTextInput) => ipcRenderer.invoke('chat:send-text', input),
    onProgress: (callback: (event: AgentProgressEvent) => void) => {
      const listener = (_event: IpcRendererEvent, event: AgentProgressEvent) => callback(event)
      ipcRenderer.on('chat:agent-progress', listener)
      return () => ipcRenderer.removeListener('chat:agent-progress', listener)
    },
  },
  voice: {
    startSession: () => ipcRenderer.invoke('voice:start-session'),
    pushAudio: (input: VoicePushAudioInput) => ipcRenderer.invoke('voice:push-audio', input),
    finishSession: (input: VoiceFinishSessionInput) => ipcRenderer.invoke('voice:finish-session', input),
    cancelSession: (input: VoiceCancelSessionInput) => ipcRenderer.invoke('voice:cancel-session', input),
    getRuntimeConfig: () => ipcRenderer.invoke('voice-runtime:get-config'),
    saveRuntimeConfig: (config: VoiceRuntimeConfig) => ipcRenderer.invoke('voice-runtime:save-config', config),
    installRuntime: () => ipcRenderer.invoke('voice-runtime:install'),
    startAmbient: () => ipcRenderer.invoke('voice-runtime:start-ambient'),
    stopAmbient: () => ipcRenderer.invoke('voice-runtime:stop-ambient'),
    speak: (input: VoiceSpeakInput) => ipcRenderer.invoke('voice-runtime:speak', input),
    interrupt: () => ipcRenderer.invoke('voice-runtime:interrupt'),
    onRuntimeEvent: (callback: (event: VoiceRuntimeEvent) => void) => {
      const listener = (_event: IpcRendererEvent, event: VoiceRuntimeEvent) => callback(event)
      ipcRenderer.on('voice-runtime:event', listener)
      return () => ipcRenderer.removeListener('voice-runtime:event', listener)
    },
  },
  logs: {
    openOpenClawLog: () => ipcRenderer.invoke('logs:open-openclaw-log'),
    openFridayLog: () => ipcRenderer.invoke('logs:open-friday-log'),
  },
  vpn: {
    getConfig: () => ipcRenderer.invoke('vpn:get-config'),
    saveConfig: (config: VpnConfig) => ipcRenderer.invoke('vpn:save-config', config),
    getState: () => ipcRenderer.invoke('vpn:get-state'),
    listLocations: () => ipcRenderer.invoke('vpn:list-locations'),
    connect: () => ipcRenderer.invoke('vpn:connect'),
    disconnect: () => ipcRenderer.invoke('vpn:disconnect'),
  },
  beamng: {
    getConfig: () => ipcRenderer.invoke('beamng:get-config'),
    saveConfig: (config) => ipcRenderer.invoke('beamng:save-config', config),
    getState: () => ipcRenderer.invoke('beamng:get-state'),
    detectInstalls: () => ipcRenderer.invoke('beamng:detect-installs'),
    installDependencies: () => ipcRenderer.invoke('beamng:install-dependencies'),
    connect: () => ipcRenderer.invoke('beamng:connect'),
    disconnect: () => ipcRenderer.invoke('beamng:disconnect'),
    listWaypoints: () => ipcRenderer.invoke('beamng:list-waypoints'),
    resolveTextCommand: (input) => ipcRenderer.invoke('beamng:resolve-text-command', input),
    executeCommand: (input) => ipcRenderer.invoke('beamng:execute-command', input),
  },
  window: {
    getState: () => ipcRenderer.invoke('window:get-state'),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
    close: () => ipcRenderer.invoke('window:close'),
  },
  backend: {
    getConfig: () => ipcRenderer.invoke('backend:get-config'),
    saveConfig: (config: BackendConfig) => ipcRenderer.invoke('backend:save-config', config),
    getSessionState: () => ipcRenderer.invoke('backend:get-session-state'),
    saveSessionState: (state: BackendSessionState) => ipcRenderer.invoke('backend:save-session-state', state),
    clearSessionState: () => ipcRenderer.invoke('backend:clear-session-state'),
    ensureLocalSession: (input: LocalSessionInput) => ipcRenderer.invoke('backend:ensure-local-session', input),
    register: (input: AuthRegisterInput) => ipcRenderer.invoke('backend:register', input),
    login: (input: AuthLoginInput) => ipcRenderer.invoke('backend:login', input),
    createAppToken: (input: CreateAppTokenInput) => ipcRenderer.invoke('backend:create-app-token', input),
    getMe: () => ipcRenderer.invoke('backend:get-me'),
    updateSettings: (input: UpdateSettingsInput) => ipcRenderer.invoke('backend:update-settings', input),
    getMessageQuota: () => ipcRenderer.invoke('backend:get-message-quota'),
    consumeMessageQuota: (input) => ipcRenderer.invoke('backend:consume-message-quota', input),
    getAgentMailAccount: () => ipcRenderer.invoke('backend:get-agent-mail-account'),
    getAgentMailMessage: (id: string) => ipcRenderer.invoke('backend:get-agent-mail-message', id),
    upsertAgentMailAccount: (input: UpsertAgentMailAccountInput) =>
      ipcRenderer.invoke('backend:upsert-agent-mail-account', input),
    listAgentMailMessages: (input?: ListAgentMailMessagesInput) =>
      ipcRenderer.invoke('backend:list-agent-mail-messages', input),
    listAgentMailContacts: (input?: ListAgentMailContactsInput) =>
      ipcRenderer.invoke('backend:list-agent-mail-contacts', input),
    upsertAgentMailContact: (input: UpsertAgentMailContactInput) =>
      ipcRenderer.invoke('backend:upsert-agent-mail-contact', input),
    deleteAgentMailContact: (id: string) => ipcRenderer.invoke('backend:delete-agent-mail-contact', id),
    createAgentMailMessage: (input: CreateAgentMailMessageInput) =>
      ipcRenderer.invoke('backend:create-agent-mail-message', input),
    markAgentMailMessageRead: (id: string) => ipcRenderer.invoke('backend:mark-agent-mail-message-read', id),
    listNotes: () => ipcRenderer.invoke('backend:list-notes'),
    createNote: (input: CreateNoteInput) => ipcRenderer.invoke('backend:create-note', input),
    updateNote: (id: string, input: UpdateNoteInput) => ipcRenderer.invoke('backend:update-note', id, input),
    deleteNote: (id: string) => ipcRenderer.invoke('backend:delete-note', id),
    listTasks: () => ipcRenderer.invoke('backend:list-tasks'),
    createTask: (input: CreateTaskInput) => ipcRenderer.invoke('backend:create-task', input),
    updateTask: (id: string, input: UpdateTaskInput) => ipcRenderer.invoke('backend:update-task', id, input),
    deleteTask: (id: string) => ipcRenderer.invoke('backend:delete-task', id),
    listReminders: () => ipcRenderer.invoke('backend:list-reminders'),
    createReminder: (input: CreateReminderInput) => ipcRenderer.invoke('backend:create-reminder', input),
    updateReminder: (id: string, input: UpdateReminderInput) =>
      ipcRenderer.invoke('backend:update-reminder', id, input),
    deleteReminder: (id: string) => ipcRenderer.invoke('backend:delete-reminder', id),
    listInbox: () => ipcRenderer.invoke('backend:list-inbox'),
    markInboxRead: (id: string) => ipcRenderer.invoke('backend:mark-inbox-read', id),
    listMemories: (query?: string) => ipcRenderer.invoke('backend:list-memories', query),
    getMemory: (id: string) => ipcRenderer.invoke('backend:get-memory', id),
    createMemory: (input: CreateMemoryInput) => ipcRenderer.invoke('backend:create-memory', input),
    updateMemory: (id: string, input: UpdateMemoryInput) => ipcRenderer.invoke('backend:update-memory', id, input),
    deleteMemory: (id: string) => ipcRenderer.invoke('backend:delete-memory', id),
    getAgentContext: () => ipcRenderer.invoke('backend:get-agent-context'),
    getUserDataOverview: () => ipcRenderer.invoke('backend:get-user-data-overview'),
    syncUserDataNow: () => ipcRenderer.invoke('backend:sync-user-data-now'),
    getUserDataSnapshot: () => ipcRenderer.invoke('backend:get-user-data-snapshot'),
    searchUserDataEntities: (input?: AgentUserDataSearchInput) =>
      ipcRenderer.invoke('backend:search-user-data-entities', input),
    getUserDataEntity: (input: AgentEntityReference) => ipcRenderer.invoke('backend:get-user-data-entity', input),
    runEcosystemUserDataAction: (input: EcosystemUserDataActionRequest) =>
      ipcRenderer.invoke('backend:run-ecosystem-user-data-action', input),
    sendAgentMessage: (input: AgentMessageInput) => ipcRenderer.invoke('backend:send-agent-message', input),
    runAgentAction: (input: AgentActionRequest) => ipcRenderer.invoke('backend:run-agent-action', input),
    confirmAgentAction: (input: AgentConfirmationInput) => ipcRenderer.invoke('backend:confirm-agent-action', input),
  },
}

contextBridge.exposeInMainWorld('friday', api)
